version: '2'


services:
    nginx:
        container_name: nginxas
        image: daocloud.io/library/nginx:latest
        ports:
        - 80:80
        volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        volumes_from:
        - php
    php:
        container_name: phpas
        build:
            context: ./php
            dockerfile: Dockerfile
        ports:
            - 9501:9501
        expose:
            - 9000
            - 9501
        volumes:
            - /var/www/html:/var/www/html:rw